//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanatorium.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int DoctorId { get; set; }
        public System.DateTime Working_hours { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
